AWSTemplateFormatVersion: 2010-09-09
Description: ECS cluster.

Parameters:
  VpcId:
    Type: String
    Description: The VPC this cluster belongs to.
  AppSubnetIds:
    Type: CommaDelimitedList
    Description: The subnet IDs of the application (private) layer.
  EC2KeyName:
    Type: String
    Description: The name of the EC2 keypair to use on all instances.
  InstanceType:
    Type: String
    Description: The EC2 instance type to host Docker.
    Default: t2.medium
  EcsAMI:
    Type: String
    Description: ECS AMI to use for the launch config.
  ASGMaxSize:
    Type: Number
    Description: Max allowed size for the AutoScaling group.
    Default: 10
  ASGMinSize:
    Type: Number
    Description: Minimum allowed size for the AutoScaling group.
    Default: 3
  ASGDesiredSize:
    Type: Number
    Description: Desired capacity for the AutoScaling group.
    Default: 3

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['ecs:DeregisterContainerInstance', 'ecs:DiscoverPollEndpoint',
              'ecs:Poll', 'ecs:RegisterContainerInstance', 'ecs:StartTelemetrySession',
              'ecs:Submit*', 'ecr:GetAuthorizationToken', 'ecr:BatchGetImage',
              'ecr:GetDownloadUrlForLayer', 'logs:CreateLogStream', 'logs:PutLogEvents']
            Resource: '*'
          - Effect: Allow
            Action: ['kms:*']
            Resource: '*'
          - Effect: Allow
            Action: ['dynamodb:*']
            Resource: '*'

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref EC2Role

  ECSCluster:
    Type: AWS::ECS::Cluster

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}
      RetentionInDays: 30

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref EcsAMI
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref Ec2InstanceProfile
      KeyName: !Ref EC2KeyName
      AssociatePublicIpAddress: True
      SecurityGroups:
      - !Ref SecurityGroup
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          yum update -y
          yum install -y aws-cli
          yum install -y awslogs
          # set up the ECS config
          cat >> /etc/ecs/ecs.config <<EoConf
          ECS_CLUSTER=${ECSCluster}
          EoConf
          # set up the default log driver to talk to CloudWatch
          cat >> /etc/sysconfig/docker <<EoDC
          OPTIONS="\$OPTIONS --log-driver=awslogs --log-opt awslogs-region=${AWS::Region} --log-opt awslogs-group=${LogGroup}"
          EoDC
          stop ecs
          start ecs

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 1
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      VPCZoneIdentifier: !Ref AppSubnetIds
      MaxSize: !Ref ASGMaxSize
      MinSize: !Ref ASGMinSize
      DesiredCapacity: !Ref ASGDesiredSize
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}
        PropagateAtLaunch: true

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permit traffic from ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 32768
        ToPort: 61000
        SourceSecurityGroupId: !Ref ALBSecurityGroup

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permit traffic to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

Outputs:
  OpsECSCluster:
    Value: !Ref ECSCluster
    Description: "Outputs the name of the ECS cluster"

  OpsALBSecurityGroup:
    Value: !Ref ALBSecurityGroup
    Description: "Outputs the ID of the ALB security group"
