steps:
  - label: Create temp network stack
    command: make test
    agents:
      queue: central-dev

  - wait

  - label: Delete temp network stack
    command: make delete-test
    agents:
      queue: central-dev
