steps:
  - label: Create temp network stack
    command: make buildStack STACK_NAME=ecs-network-temp CFN_LOCATION=network/template.yml CFN_PARAMS=network/params.json
    agents:
      queue: central-dev