steps:
  - label: Create full stack in Oregon (us-west-2)
    command: make test
    agents:
      queue: central-dev

  - wait

  - label: Delete full stack in Oregon (us-west-2)
    command: make delete-test
    agents:
      queue: central-dev
