steps:
  - label: Create temp network stack
    command: make buildStack STACK_NAME=services-network-temp CFN_LOCATION=network/template.yml CFN_PARAMS=network/params.json
    agents:
      queue: central-dev

  - wait

  - label: Delete temp network stack
    command: make deleteStack STACK_NAME=services-network-temp
    agents:
      queue: central-dev